spec:
  containers:
  - name: qdrant
    image: qdrant/qdrant:latest
    ports:
    - containerPort: 6333
    - containerPort: 6334
    resources:
      requests:
        cpu: "500m"        # Request 0.5 CPU cores
        memory: "1Gi"      # Request 1GB of memory
      limits:
        cpu: "2"           # Limit to 2 CPU cores
        memory: "4Gi"      # Limit to 4GB of memory
    volumeMounts:
    - name: qdrant-storage
      mountPath: /qdrant/storage
  volumes:
  - name: qdrant-storage
    persistentVolumeClaim:
      claimName: qdrant-pvc